export const COUNTRY_CODE = [
  {
    name: 'Afghanistan (+93)',
    dial_code: '+93',
    code: 'AF',
    id: 'AF',
  },
  {
    name: 'Aland Islands (+358)',
    dial_code: '+358',
    code: 'AX',
    id: 'AX',
  },
  {
    name: 'Albania (+355)',
    dial_code: '+355',
    code: 'AL',
    id: 'AL',
  },
  {
    name: 'Algeria (+213)',
    dial_code: '+213',
    code: 'DZ',
    id: 'DZ',
  },
  {
    name: 'AmericanSamoa (+1684)',
    dial_code: '+1684',
    code: 'AS',
    id: 'AS',
  },
  {
    name: 'Andorra (+376)',
    dial_code: '+376',
    code: 'AD',
    id: 'AD',
  },
  {
    name: 'Angola (+244)',
    dial_code: '+244',
    code: 'AO',
    id: 'AO',
  },
  {
    name: 'Anguilla (+1264)',
    dial_code: '+1264',
    code: 'AI',
    id: 'AI',
  },
  {
    name: 'Antarctica (+672)',
    dial_code: '+672',
    code: 'AQ',
    id: 'AQ',
  },
  {
    name: 'Antigua and Barbuda (+1268)',
    dial_code: '+1268',
    code: 'AG',
    id: 'AG',
  },
  {
    name: 'Argentina (+54)',
    dial_code: '+54',
    code: 'AR',
    id: 'AR',
  },
  {
    name: 'Armenia (+374)',
    dial_code: '+374',
    code: 'AM',
    id: 'AM',
  },
  {
    name: 'Aruba (+297)',
    dial_code: '+297',
    code: 'AW',
    id: 'AW',
  },
  {
    name: 'Australia (+61)',
    dial_code: '+61',
    code: 'AU',
    id: 'AU',
  },
  {
    name: 'Austria (+43)',
    dial_code: '+43',
    code: 'AT',
    id: 'AT',
  },
  {
    name: 'Azerbaijan (+994)',
    dial_code: '+994',
    code: 'AZ',
    id: 'AZ',
  },
  {
    name: 'Bahamas (+1242)',
    dial_code: '+1242',
    code: 'BS',
    id: 'BS',
  },
  {
    name: 'Bahrain (+973)',
    dial_code: '+973',
    code: 'BH',
    id: 'BH',
  },
  {
    name: 'Bangladesh (+880)',
    dial_code: '+880',
    code: 'BD',
    id: 'BD',
  },
  {
    name: 'Barbados (+1246)',
    dial_code: '+1246',
    code: 'BB',
    id: 'BB',
  },
  {
    name: 'Belarus (+375)',
    dial_code: '+375',
    code: 'BY',
    id: 'BY',
  },
  {
    name: 'Belgium (+32)',
    dial_code: '+32',
    code: 'BE',
    id: 'BE',
  },
  {
    name: 'Belize (+501)',
    dial_code: '+501',
    code: 'BZ',
    id: 'BZ',
  },
  {
    name: 'Benin (+229)',
    dial_code: '+229',
    code: 'BJ',
    id: 'BJ',
  },
  {
    name: 'Bermuda (+1441)',
    dial_code: '+1441',
    code: 'BM',
    id: 'BM',
  },
  {
    name: 'Bhutan (+975)',
    dial_code: '+975',
    code: 'BT',
    id: 'BT',
  },
  {
    name: 'Bolivia, Plurinational State of (+591)',
    dial_code: '+591',
    code: 'BO',
    id: 'BO',
  },
  {
    name: 'Bosnia and Herzegovina (+387)',
    dial_code: '+387',
    code: 'BA',
    id: 'BA',
  },
  {
    name: 'Botswana (+267)',
    dial_code: '+267',
    code: 'BW',
    id: 'BW',
  },
  {
    name: 'Brazil (+55)',
    dial_code: '+55',
    code: 'BR',
    id: 'BR',
  },
  {
    name: 'British Indian Ocean Territory (+246)',
    dial_code: '+246',
    code: 'IO',
    id: 'IO',
  },
  {
    name: 'Brunei Darussalam (+673)',
    dial_code: '+673',
    code: 'BN',
    id: 'BN',
  },
  {
    name: 'Bulgaria (+359)',
    dial_code: '+359',
    code: 'BG',
    id: 'BG',
  },
  {
    name: 'Burkina Faso (+226)',
    dial_code: '+226',
    code: 'BF',
    id: 'BF',
  },
  {
    name: 'Burundi (+257)',
    dial_code: '+257',
    code: 'BI',
    id: 'BI',
  },
  {
    name: 'Cambodia (+855)',
    dial_code: '+855',
    code: 'KH',
    id: 'KH',
  },
  {
    name: 'Cameroon (+237)',
    dial_code: '+237',
    code: 'CM',
    id: 'CM',
  },
  {
    name: 'Canada (+1)',
    dial_code: '+1',
    code: 'CA',
    id: 'CA',
  },
  {
    name: 'Cape Verde (+238)',
    dial_code: '+238',
    code: 'CV',
    id: 'CV',
  },
  {
    name: 'Cayman Islands (+ 345)',
    dial_code: '+ 345',
    code: 'KY',
    id: 'KY',
  },
  {
    name: 'Central African Republic (+236)',
    dial_code: '+236',
    code: 'CF',
    id: 'CF',
  },
  {
    name: 'Chad (+235)',
    dial_code: '+235',
    code: 'TD',
    id: 'TD',
  },
  {
    name: 'Chile (+56)',
    dial_code: '+56',
    code: 'CL',
    id: 'CL',
  },
  {
    name: 'China (+86)',
    dial_code: '+86',
    code: 'CN',
    id: 'CN',
  },
  {
    name: 'Christmas Island (+61)',
    dial_code: '+61',
    code: 'CX',
    id: 'CX',
  },
  {
    name: 'Cocos (Keeling) Islands (+61)',
    dial_code: '+61',
    code: 'CC',
    id: 'CC',
  },
  {
    name: 'Colombia (+57)',
    dial_code: '+57',
    code: 'CO',
    id: 'CO',
  },
  {
    name: 'Comoros (+269)',
    dial_code: '+269',
    code: 'KM',
    id: 'KM',
  },
  {
    name: 'Congo (+242)',
    dial_code: '+242',
    code: 'CG',
    id: 'CG',
  },
  {
    name: 'Congo, The Democratic Republic of the Congo (+243)',
    dial_code: '+243',
    code: 'CD',
    id: 'CD',
  },
  {
    name: 'Cook Islands (+682)',
    dial_code: '+682',
    code: 'CK',
    id: 'CK',
  },
  {
    name: 'Costa Rica (+506)',
    dial_code: '+506',
    code: 'CR',
    id: 'CR',
  },
  {
    name: "Cote d'Ivoire (+225)",
    dial_code: '+225',
    code: 'CI',
    id: 'CI',
  },
  {
    name: 'Croatia (+385)',
    dial_code: '+385',
    code: 'HR',
    id: 'HR',
  },
  {
    name: 'Cuba (+53)',
    dial_code: '+53',
    code: 'CU',
    id: 'CU',
  },
  {
    name: 'Cyprus (+357)',
    dial_code: '+357',
    code: 'CY',
    id: 'CY',
  },
  {
    name: 'Czech Republic (+420)',
    dial_code: '+420',
    code: 'CZ',
    id: 'CZ',
  },
  {
    name: 'Denmark (+45)',
    dial_code: '+45',
    code: 'DK',
    id: 'DK',
  },
  {
    name: 'Djibouti (+253)',
    dial_code: '+253',
    code: 'DJ',
    id: 'DJ',
  },
  {
    name: 'Dominica (+1767)',
    dial_code: '+1767',
    code: 'DM',
    id: 'DM',
  },
  {
    name: 'Dominican Republic (+1849)',
    dial_code: '+1849',
    code: 'DO',
    id: 'DO',
  },
  {
    name: 'Ecuador (+593)',
    dial_code: '+593',
    code: 'EC',
    id: 'EC',
  },
  {
    name: 'Egypt (+20)',
    dial_code: '+20',
    code: 'EG',
    id: 'EG',
  },
  {
    name: 'El Salvador (+503)',
    dial_code: '+503',
    code: 'SV',
    id: 'SV',
  },
  {
    name: 'Equatorial Guinea (+240)',
    dial_code: '+240',
    code: 'GQ',
    id: 'GQ',
  },
  {
    name: 'Eritrea (+291)',
    dial_code: '+291',
    code: 'ER',
    id: 'ER',
  },
  {
    name: 'Estonia (+372)',
    dial_code: '+372',
    code: 'EE',
    id: 'EE',
  },
  {
    name: 'Ethiopia (+251)',
    dial_code: '+251',
    code: 'ET',
    id: 'ET',
  },
  {
    name: 'Falkland Islands (Malvinas) (+500)',
    dial_code: '+500',
    code: 'FK',
    id: 'FK',
  },
  {
    name: 'Faroe Islands (+298)',
    dial_code: '+298',
    code: 'FO',
    id: 'FO',
  },
  {
    name: 'Fiji (+679)',
    dial_code: '+679',
    code: 'FJ',
    id: 'FJ',
  },
  {
    name: 'Finland (+358)',
    dial_code: '+358',
    code: 'FI',
    id: 'FI',
  },
  {
    name: 'France (+33)',
    dial_code: '+33',
    code: 'FR',
    id: 'FR',
  },
  {
    name: 'French Guiana (+594)',
    dial_code: '+594',
    code: 'GF',
    id: 'GF',
  },
  {
    name: 'French Polynesia (+689)',
    dial_code: '+689',
    code: 'PF',
    id: 'PF',
  },
  {
    name: 'Gabon (+241)',
    dial_code: '+241',
    code: 'GA',
    id: 'GA',
  },
  {
    name: 'Gambia (+220)',
    dial_code: '+220',
    code: 'GM',
    id: 'GM',
  },
  {
    name: 'Georgia (+995)',
    dial_code: '+995',
    code: 'GE',
    id: 'GE',
  },
  {
    name: 'Germany (+49)',
    dial_code: '+49',
    code: 'DE',
    id: 'DE',
  },
  {
    name: 'Ghana (+233)',
    dial_code: '+233',
    code: 'GH',
    id: 'GH',
  },
  {
    name: 'Gibraltar (+350)',
    dial_code: '+350',
    code: 'GI',
    id: 'GI',
  },
  {
    name: 'Greece (+30)',
    dial_code: '+30',
    code: 'GR',
    id: 'GR',
  },
  {
    name: 'Greenland (+299)',
    dial_code: '+299',
    code: 'GL',
    id: 'GL',
  },
  {
    name: 'Grenada (+1473)',
    dial_code: '+1473',
    code: 'GD',
    id: 'GD',
  },
  {
    name: 'Guadeloupe (+590)',
    dial_code: '+590',
    code: 'GP',
    id: 'GP',
  },
  {
    name: 'Guam (+1671)',
    dial_code: '+1671',
    code: 'GU',
    id: 'GU',
  },
  {
    name: 'Guatemala (+502)',
    dial_code: '+502',
    code: 'GT',
    id: 'GT',
  },
  {
    name: 'Guernsey (+44)',
    dial_code: '+44',
    code: 'GG',
    id: 'GG',
  },
  {
    name: 'Guinea (+224)',
    dial_code: '+224',
    code: 'GN',
    id: 'GN',
  },
  {
    name: 'Guinea-Bissau (+245)',
    dial_code: '+245',
    code: 'GW',
    id: 'GW',
  },
  {
    name: 'Guyana (+595)',
    dial_code: '+595',
    code: 'GY',
    id: 'GY',
  },
  {
    name: 'Haiti (+509)',
    dial_code: '+509',
    code: 'HT',
    id: 'HT',
  },
  {
    name: 'Holy See (Vatican City State) (+379)',
    dial_code: '+379',
    code: 'VA',
    id: 'VA',
  },
  {
    name: 'Honduras (+504)',
    dial_code: '+504',
    code: 'HN',
    id: 'HN',
  },
  {
    name: 'Hong Kong (+852)',
    dial_code: '+852',
    code: 'HK',
    id: 'HK',
  },
  {
    name: 'Hungary (+36)',
    dial_code: '+36',
    code: 'HU',
    id: 'HU',
  },
  {
    name: 'Iceland (+354)',
    dial_code: '+354',
    code: 'IS',
    id: 'IS',
  },
  {
    name: 'India (+91)',
    dial_code: '+91',
    code: 'IN',
    id: 'IN',
  },
  {
    name: 'Indonesia (+62)',
    dial_code: '+62',
    code: 'ID',
    id: 'ID',
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf (+98)',
    dial_code: '+98',
    code: 'IR',
    id: 'IR',
  },
  {
    name: 'Iraq (+964)',
    dial_code: '+964',
    code: 'IQ',
    id: 'IQ',
  },
  {
    name: 'Ireland (+353)',
    dial_code: '+353',
    code: 'IE',
    id: 'IE',
  },
  {
    name: 'Isle of Man (+44)',
    dial_code: '+44',
    code: 'IM',
    id: 'IM',
  },
  {
    name: 'Israel (+972)',
    dial_code: '+972',
    code: 'IL',
    id: 'IL',
  },
  {
    name: 'Italy (+39)',
    dial_code: '+39',
    code: 'IT',
    id: 'IT',
  },
  {
    name: 'Jamaica (+1876)',
    dial_code: '+1876',
    code: 'JM',
    id: 'JM',
  },
  {
    name: 'Japan (+81)',
    dial_code: '+81',
    code: 'JP',
    id: 'JP',
  },
  {
    name: 'Jersey (+44)',
    dial_code: '+44',
    code: 'JE',
    id: 'JE',
  },
  {
    name: 'Jordan (+962)',
    dial_code: '+962',
    code: 'JO',
    id: 'JO',
  },
  {
    name: 'Kazakhstan (+77)',
    dial_code: '+77',
    code: 'KZ',
    id: 'KZ',
  },
  {
    name: 'Kenya (+254)',
    dial_code: '+254',
    code: 'KE',
    id: 'KE',
  },
  {
    name: 'Kiribati (+686)',
    dial_code: '+686',
    code: 'KI',
    id: 'KI',
  },
  {
    name: "Korea, Democratic People's Republic of Korea (+850)",
    dial_code: '+850',
    code: 'KP',
    id: 'KP',
  },
  {
    name: 'Korea, Republic of South Korea (+82)',
    dial_code: '+82',
    code: 'KR',
    id: 'KR',
  },
  {
    name: 'Kuwait (+965)',
    dial_code: '+965',
    code: 'KW',
    id: 'KW',
  },
  {
    name: 'Kyrgyzstan (+996)',
    dial_code: '+996',
    code: 'KG',
    id: 'KG',
  },
  {
    name: 'Laos (+856)',
    dial_code: '+856',
    code: 'LA',
    id: 'LA',
  },
  {
    name: 'Latvia (+371)',
    dial_code: '+371',
    code: 'LV',
    id: 'LV',
  },
  {
    name: 'Lebanon (+961)',
    dial_code: '+961',
    code: 'LB',
    id: 'LB',
  },
  {
    name: 'Lesotho (+266)',
    dial_code: '+266',
    code: 'LS',
    id: 'LS',
  },
  {
    name: 'Liberia (+231)',
    dial_code: '+231',
    code: 'LR',
    id: 'LR',
  },
  {
    name: 'Libyan Arab Jamahiriya (+218)',
    dial_code: '+218',
    code: 'LY',
    id: 'LY',
  },
  {
    name: 'Liechtenstein (+423)',
    dial_code: '+423',
    code: 'LI',
    id: 'LI',
  },
  {
    name: 'Lithuania (+370)',
    dial_code: '+370',
    code: 'LT',
    id: 'LT',
  },
  {
    name: 'Luxembourg (+352)',
    dial_code: '+352',
    code: 'LU',
    id: 'LU',
  },
  {
    name: 'Macao (+853)',
    dial_code: '+853',
    code: 'MO',
    id: 'MO',
  },
  {
    name: 'Macedonia (+389)',
    dial_code: '+389',
    code: 'MK',
    id: 'MK',
  },
  {
    name: 'Madagascar (+261)',
    dial_code: '+261',
    code: 'MG',
    id: 'MG',
  },
  {
    name: 'Malawi (+265)',
    dial_code: '+265',
    code: 'MW',
    id: 'MW',
  },
  {
    name: 'Malaysia (+60)',
    dial_code: '+60',
    code: 'MY',
    id: 'MY',
  },
  {
    name: 'Maldives (+960)',
    dial_code: '+960',
    code: 'MV',
    id: 'MV',
  },
  {
    name: 'Mali (+223)',
    dial_code: '+223',
    code: 'ML',
    id: 'ML',
  },
  {
    name: 'Malta (+356)',
    dial_code: '+356',
    code: 'MT',
    id: 'MT',
  },
  {
    name: 'Marshall Islands (+692)',
    dial_code: '+692',
    code: 'MH',
    id: 'MH',
  },
  {
    name: 'Martinique (+596)',
    dial_code: '+596',
    code: 'MQ',
    id: 'MQ',
  },
  {
    name: 'Mauritania (+222)',
    dial_code: '+222',
    code: 'MR',
    id: 'MR',
  },
  {
    name: 'Mauritius (+230)',
    dial_code: '+230',
    code: 'MU',
    id: 'MU',
  },
  {
    name: 'Mayotte (+262)',
    dial_code: '+262',
    code: 'YT',
    id: 'YT',
  },
  {
    name: 'Mexico (+52)',
    dial_code: '+52',
    code: 'MX',
    id: 'MX',
  },
  {
    name: 'Micronesia, Federated States of Micronesia (+691)',
    dial_code: '+691',
    code: 'FM',
    id: 'FM',
  },
  {
    name: 'Moldova (+373)',
    dial_code: '+373',
    code: 'MD',
    id: 'MD',
  },
  {
    name: 'Monaco (+377)',
    dial_code: '+377',
    code: 'MC',
    id: 'MC',
  },
  {
    name: 'Mongolia (+976)',
    dial_code: '+976',
    code: 'MN',
    id: 'MN',
  },
  {
    name: 'Montenegro (+382)',
    dial_code: '+382',
    code: 'ME',
    id: 'ME',
  },
  {
    name: 'Montserrat (+1664)',
    dial_code: '+1664',
    code: 'MS',
    id: 'MS',
  },
  {
    name: 'Morocco (+212)',
    dial_code: '+212',
    code: 'MA',
    id: 'MA',
  },
  {
    name: 'Mozambique (+258)',
    dial_code: '+258',
    code: 'MZ',
    id: 'MZ',
  },
  {
    name: 'Myanmar (+95)',
    dial_code: '+95',
    code: 'MM',
    id: 'MM',
  },
  {
    name: 'Namibia (+264)',
    dial_code: '+264',
    code: 'NA',
    id: 'NA',
  },
  {
    name: 'Nauru (+674)',
    dial_code: '+674',
    code: 'NR',
    id: 'NR',
  },
  {
    name: 'Nepal (+977)',
    dial_code: '+977',
    code: 'NP',
    id: 'NP',
  },
  {
    name: 'Netherlands (+31)',
    dial_code: '+31',
    code: 'NL',
    id: 'NL',
  },
  {
    name: 'Netherlands Antilles (+599)',
    dial_code: '+599',
    code: 'AN',
    id: 'AN',
  },
  {
    name: 'New Caledonia (+687)',
    dial_code: '+687',
    code: 'NC',
    id: 'NC',
  },
  {
    name: 'New Zealand (+64)',
    dial_code: '+64',
    code: 'NZ',
    id: 'NZ',
  },
  {
    name: 'Nicaragua (+505)',
    dial_code: '+505',
    code: 'NI',
    id: 'NI',
  },
  {
    name: 'Niger (+227)',
    dial_code: '+227',
    code: 'NE',
    id: 'NE',
  },
  {
    name: 'Nigeria (+234)',
    dial_code: '+234',
    code: 'NG',
    id: 'NG',
  },
  {
    name: 'Niue (+683)',
    dial_code: '+683',
    code: 'NU',
    id: 'NU',
  },
  {
    name: 'Norfolk Island (+672)',
    dial_code: '+672',
    code: 'NF',
    id: 'NF',
  },
  {
    name: 'Northern Mariana Islands (+1670)',
    dial_code: '+1670',
    code: 'MP',
    id: 'MP',
  },
  {
    name: 'Norway (+47)',
    dial_code: '+47',
    code: 'NO',
    id: 'NO',
  },
  {
    name: 'Oman (+968)',
    dial_code: '+968',
    code: 'OM',
    id: 'OM',
  },
  {
    name: 'Pakistan (+92)',
    dial_code: '+92',
    code: 'PK',
    id: 'PK',
  },
  {
    name: 'Palau (+680)',
    dial_code: '+680',
    code: 'PW',
    id: 'PW',
  },
  {
    name: 'Palestinian Territory, Occupied (+970)',
    dial_code: '+970',
    code: 'PS',
    id: 'PS',
  },
  {
    name: 'Panama (+507)',
    dial_code: '+507',
    code: 'PA',
    id: 'PA',
  },
  {
    name: 'Papua New Guinea (+675)',
    dial_code: '+675',
    code: 'PG',
    id: 'PG',
  },
  {
    name: 'Paraguay (+595)',
    dial_code: '+595',
    code: 'PY',
    id: 'PY',
  },
  {
    name: 'Peru (+51)',
    dial_code: '+51',
    code: 'PE',
    id: 'PE',
  },
  {
    name: 'Philippines (+63)',
    dial_code: '+63',
    code: 'PH',
    id: 'PH',
  },
  {
    name: 'Pitcairn (+872)',
    dial_code: '+872',
    code: 'PN',
    id: 'PN',
  },
  {
    name: 'Poland (+48)',
    dial_code: '+48',
    code: 'PL',
    id: 'PL',
  },
  {
    name: 'Portugal (+351)',
    dial_code: '+351',
    code: 'PT',
    id: 'PT',
  },
  {
    name: 'Puerto Rico (+1939)',
    dial_code: '+1939',
    code: 'PR',
    id: 'PR',
  },
  {
    name: 'Qatar (+974)',
    dial_code: '+974',
    code: 'QA',
    id: 'QA',
  },
  {
    name: 'Romania (+40)',
    dial_code: '+40',
    code: 'RO',
    id: 'RO',
  },
  {
    name: 'Russia (+7)',
    dial_code: '+7',
    code: 'RU',
    id: 'RU',
  },
  {
    name: 'Rwanda (+250)',
    dial_code: '+250',
    code: 'RW',
    id: 'RW',
  },
  {
    name: 'Reunion (+262)',
    dial_code: '+262',
    code: 'RE',
    id: 'RE',
  },
  {
    name: 'Saint Barthelemy (+590)',
    dial_code: '+590',
    code: 'BL',
    id: 'BL',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha (+290)',
    dial_code: '+290',
    code: 'SH',
    id: 'SH',
  },
  {
    name: 'Saint Kitts and Nevis (+1869)',
    dial_code: '+1869',
    code: 'KN',
    id: 'KN',
  },
  {
    name: 'Saint Lucia (+1758)',
    dial_code: '+1758',
    code: 'LC',
    id: 'LC',
  },
  {
    name: 'Saint Martin (+590)',
    dial_code: '+590',
    code: 'MF',
    id: 'MF',
  },
  {
    name: 'Saint Pierre and Miquelon (+508)',
    dial_code: '+508',
    code: 'PM',
    id: 'PM',
  },
  {
    name: 'Saint Vincent and the Grenadines (+1784)',
    dial_code: '+1784',
    code: 'VC',
    id: 'VC',
  },
  {
    name: 'Samoa (+685)',
    dial_code: '+685',
    code: 'WS',
    id: 'WS',
  },
  {
    name: 'San Marino (+378)',
    dial_code: '+378',
    code: 'SM',
    id: 'SM',
  },
  {
    name: 'Sao Tome and Principe (+239)',
    dial_code: '+239',
    code: 'ST',
    id: 'ST',
  },
  {
    name: 'Saudi Arabia (+966)',
    dial_code: '+966',
    code: 'SA',
    id: 'SA',
  },
  {
    name: 'Senegal (+221)',
    dial_code: '+221',
    code: 'SN',
    id: 'SN',
  },
  {
    name: 'Serbia (+381)',
    dial_code: '+381',
    code: 'RS',
    id: 'RS',
  },
  {
    name: 'Seychelles (+248)',
    dial_code: '+248',
    code: 'SC',
    id: 'SC',
  },
  {
    name: 'Sierra Leone (+232)',
    dial_code: '+232',
    code: 'SL',
    id: 'SL',
  },
  {
    name: 'Singapore (+65)',
    dial_code: '+65',
    code: 'SG',
    id: 'SG',
  },
  {
    name: 'Slovakia (+421)',
    dial_code: '+421',
    code: 'SK',
    id: 'SK',
  },
  {
    name: 'Slovenia (+386)',
    dial_code: '+386',
    code: 'SI',
    id: 'SI',
  },
  {
    name: 'Solomon Islands (+677)',
    dial_code: '+677',
    code: 'SB',
    id: 'SB',
  },
  {
    name: 'Somalia (+252)',
    dial_code: '+252',
    code: 'SO',
    id: 'SO',
  },
  {
    name: 'South Africa (+27)',
    dial_code: '+27',
    code: 'ZA',
    id: 'ZA',
  },
  {
    name: 'South Sudan (+211)',
    dial_code: '+211',
    code: 'SS',
    id: 'SS',
  },
  {
    name: 'South Georgia and the South Sandwich Islands (+500)',
    dial_code: '+500',
    code: 'GS',
    id: 'GS',
  },
  {
    name: 'Spain (+34)',
    dial_code: '+34',
    code: 'ES',
    id: 'ES',
  },
  {
    name: 'Sri Lanka (+94)',
    dial_code: '+94',
    code: 'LK',
    id: 'LK',
  },
  {
    name: 'Sudan (+249)',
    dial_code: '+249',
    code: 'SD',
    id: 'SD',
  },
  {
    name: 'Suriname (+597)',
    dial_code: '+597',
    code: 'SR',
    id: 'SR',
  },
  {
    name: 'Svalbard and Jan Mayen (+47)',
    dial_code: '+47',
    code: 'SJ',
    id: 'SJ',
  },
  {
    name: 'Swaziland (+268)',
    dial_code: '+268',
    code: 'SZ',
    id: 'SZ',
  },
  {
    name: 'Sweden (+46)',
    dial_code: '+46',
    code: 'SE',
    id: 'SE',
  },
  {
    name: 'Switzerland (+41)',
    dial_code: '+41',
    code: 'CH',
    id: 'CH',
  },
  {
    name: 'Syrian Arab Republic (+963)',
    dial_code: '+963',
    code: 'SY',
    id: 'SY',
  },
  {
    name: 'Taiwan (+886)',
    dial_code: '+886',
    code: 'TW',
    id: 'TW',
  },
  {
    name: 'Tajikistan (+992)',
    dial_code: '+992',
    code: 'TJ',
    id: 'TJ',
  },
  {
    name: 'Tanzania, United Republic of Tanzania (+255)',
    dial_code: '+255',
    code: 'TZ',
    id: 'TZ',
  },
  {
    name: 'Thailand (+66)',
    dial_code: '+66',
    code: 'TH',
    id: 'TH',
  },
  {
    name: 'Timor-Leste (+670)',
    dial_code: '+670',
    code: 'TL',
    id: 'TL',
  },
  {
    name: 'Togo (+228)',
    dial_code: '+228',
    code: 'TG',
    id: 'TG',
  },
  {
    name: 'Tokelau (+690)',
    dial_code: '+690',
    code: 'TK',
    id: 'TK',
  },
  {
    name: 'Tonga (+676)',
    dial_code: '+676',
    code: 'TO',
    id: 'TO',
  },
  {
    name: 'Trinidad and Tobago (+1868)',
    dial_code: '+1868',
    code: 'TT',
    id: 'TT',
  },
  {
    name: 'Tunisia (+216)',
    dial_code: '+216',
    code: 'TN',
    id: 'TN',
  },
  {
    name: 'Turkey (+90)',
    dial_code: '+90',
    code: 'TR',
    id: 'TR',
  },
  {
    name: 'Turkmenistan (+993)',
    dial_code: '+993',
    code: 'TM',
    id: 'TM',
  },
  {
    name: 'Turks and Caicos Islands (+1649)',
    dial_code: '+1649',
    code: 'TC',
    id: 'TC',
  },
  {
    name: 'Tuvalu (+688)',
    dial_code: '+688',
    code: 'TV',
    id: 'TV',
  },
  {
    name: 'Uganda (+256)',
    dial_code: '+256',
    code: 'UG',
    id: 'UG',
  },
  {
    name: 'Ukraine (+380)',
    dial_code: '+380',
    code: 'UA',
    id: 'UA',
  },
  {
    name: 'United Arab Emirates (+971)',
    dial_code: '+971',
    code: 'AE',
    id: 'AE',
  },
  {
    name: 'United Kingdom (+44)',
    dial_code: '+44',
    code: 'GB',
    id: 'GB',
  },
  {
    name: 'United States (+1)',
    dial_code: '+1',
    code: 'US',
    id: 'US',
  },
  {
    name: 'Uruguay (+598)',
    dial_code: '+598',
    code: 'UY',
    id: 'UY',
  },
  {
    name: 'Uzbekistan (+998)',
    dial_code: '+998',
    code: 'UZ',
    id: 'UZ',
  },
  {
    name: 'Vanuatu (+678)',
    dial_code: '+678',
    code: 'VU',
    id: 'VU',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela (+58)',
    dial_code: '+58',
    code: 'VE',
    id: 'VE',
  },
  {
    name: 'Vietnam (+84)',
    dial_code: '+84',
    code: 'VN',
    id: 'VN',
  },
  {
    name: 'Virgin Islands, British (+1284)',
    dial_code: '+1284',
    code: 'VG',
    id: 'VG',
  },
  {
    name: 'Virgin Islands, U.S. (+1340)',
    dial_code: '+1340',
    code: 'VI',
    id: 'VI',
  },
  {
    name: 'Wallis and Futuna (+681)',
    dial_code: '+681',
    code: 'WF',
    id: 'WF',
  },
  {
    name: 'Yemen (+967)',
    dial_code: '+967',
    code: 'YE',
    id: 'YE',
  },
  {
    name: 'Zambia (+260)',
    dial_code: '+260',
    code: 'ZM',
    id: 'ZM',
  },
  {
    name: 'Zimbabwe (+263)',
    dial_code: '+263',
    code: 'ZW',
    id: 'ZW',
  },
];
